### ISSUE TITLE
What LICENSE does this have? Same as miekg/dns?

### ISSUE THREAD

**Issue by eriknordmark** [Focinfi/go-dns-resolver#3]
You say in the README it is based on [miekg/dns](https://github.com/miekg/dns) and that has a LICENSE file. Did you intend to use the same license? If so it would be helpful to add that LICENSE file.

**Comment by Focinfi** [comment]
@eriknordmark thanks 

Added the same license as [miekg/dns](https://github.com/miekg/dns)

Tag: [v1.0.1](https://github.com/Focinfi/go-dns-resolver/tree/v1.0.1)
